- name: web
  hosts: web
  become: true
  vars:
    my_variable: "Hello, Ansible!"
    ansible_port: 22
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /root/MyAWSKey.pem
  ## Example 1
  # Run on 2 instances only
  serial: 2 
  ## Example 2
  # serial:
  # # Run on one instance then 4 at a time then 2 at a time
  #   - 1
  #   - 4
  #   - 2
  ## Example 3
  # serial:
  # # Run on 50% of the instances
  #   - "50%"
  tasks:
    - name: Curl AWS
      shell: curl localhost
      args:
        chdir: /home/ubuntu/
        executable: /bin/bash
      register: curl
    - name: Print "Hello World!"
      debug:
        # msg: "Hello World!"
        # changed | cmd | delta | end | msg | rc | start | stderr | stderr_lines | stdout | stdout_lines
        var: curl.cmd        