apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  LOGGING_FORMAT: "json"
  DATABASE_HOST: "mysql-service"
  DATABASE_PORT: "3306"
  DATABASE_DB: "mydb"
  DATABASE_USER: "root"

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # Base64 encoded 'root'
  DATABASE_PASSWORD: cm9vdA== # Base64 encoded 'root'
