trigger:
- master

# example variables 
# (Pipeline.Workspace) (Build.BuildId)
variables:
  vmImageName: 'ubuntu-latest'
  environmentName: 'production'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.7'

stages: 
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build_job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: "execute some script 1"  
      inputs:
        targetType: 'inline'
        script: |
          echo Init 1
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - deployment: DeploymentJob
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : appname'
            inputs:
              appType: webApp
              azureSubscription: $(azureServiceConnectionId)
              appName: appname
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
