trigger:
- master

# example variables 
# (Pipeline.Workspace) (Build.BuildId)
variables:
  vmImageName: 'ubuntu-latest'
  environmentName: 'production'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.7'

stages: 
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: execute some script 1
    - script: | 
        echo BUILD 1
      workingDirectory: $(projectRoot)
    - task: Bash@3
      displayName: execute some script 2
    - script: | 
        echo BUILD 2
      workingDirectory: $(projectRoot)      
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - deployment: DeploymentJob
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : appname'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: appname
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
