- hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: Display first Value
      debug:
        msg: "{{ http_port }}"
    - name: Display second Value
      debug:
        msg: "{{ server_name }}"
