{
 "title": "Docker Monitoring",
 "description": "Simple exporter for cadvisor only",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(instance) (rate(container_last_seen{name=~\".+\", instance=~\"$host\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (container_memory_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$host\", job=\"cadvisor\"}[5m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cached Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(\r\n  container_memory_cache{instance=~\"$host\", name=~\"$container\", name=~\".+\"}\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m]))\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(container_fs_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
     "legendFormat": "{{instance}} IO"
    }
   ]
  },
  {
   "title": "Write Bytes Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(container_fs_writes_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
     "legendFormat": "{{instance}} Write"
    }
   ]
  },
  {
   "title": "Read Bytes Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(container_fs_reads_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
     "legendFormat": "{{instance}} Read"
    }
   ]
  },
  {
   "title": "IO $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(name) (rate(container_fs_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "IO Usage Total",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(name) (container_fs_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Write Usage",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(name) (container_fs_writes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Reads Usage",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(name) (container_fs_reads_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Read Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(name) (rate(container_fs_reads_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Write Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(name) (rate(container_fs_writes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[15m]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 17, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$host\", job=\"cadvisor\"}[5m])) * 100",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "CPU By containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m])) by (name)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Usage memory",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{name=~\".+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum(container_memory_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"}) by (name))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Total Cached Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum(container_memory_cache{instance=~\"$host\", name=~\"$container\", name=~\".+\"}) by (name))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(name) (container_memory_usage_bytes{instance=~\"$host\", name=~\"$container\", name=~\".+\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_cache{instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Received Network Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(rate(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m])) by (name))\r\n",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total Sent Network Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(rate(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m])) by (name))\r\n",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Received Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}