{
 "title": "Jenkins Dashboard Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(default_jenkins_up,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(default_jenkins_up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "jenkins_job",
    "label": "Jenkins Job Name",
    "query": {
     "query": "label_values(default_jenkins_builds_available_builds_count{job=~\"$job\"},jenkins_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jenkins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_up{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_version_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_uptime{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_count_value{job=~\"$job\",instance=~\"$instance\"} -1"
    }
   ]
  },
  {
   "title": "Agents Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_nodes_online{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Jobs Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_count_value{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins IO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_file_store_capacity_bytes{job=~\"$job\", instance=~\"$instance\", file_store=\"/ (rootfs)\"}",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "default_jenkins_file_store_available_bytes{job=~\"$job\", instance=~\"$instance\", file_store=\"/ (rootfs)\"}",
     "legendFormat": "FREE"
    },
    {
     "expr": "default_jenkins_file_store_capacity_bytes{job=~\"$job\", instance=~\"$instance\", file_store=\"/ (rootfs)\"} - default_jenkins_file_store_available_bytes{job=~\"$job\", instance=~\"$instance\", file_store=\"/ (rootfs)\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Jenkins Executors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_count_value{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_active{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Outdated Plugins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_withUpdate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Enabled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disabled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Agents Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jenkins Build Count Per Node",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "jenkins_node_builds_count{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Running Executor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "default_jenkins_executors_busy{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Available Executor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "default_jenkins_executors_available{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Idle Executor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "default_jenkins_executors_idle{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Last Build Duration",
     "type": "table",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(50, default_jenkins_builds_last_build_duration_milliseconds{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"})",
       "legendFormat": "{{jenkins_job}}"
      }
     ]
    },
    {
     "title": "Average Job Duration",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(50,avg by (jenkins_job) (default_jenkins_builds_duration_milliseconds_summary_sum{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"}) / avg by (jenkins_job) (default_jenkins_builds_available_builds_count{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Score",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "default_jenkins_builds_health_score{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"}",
       "legendFormat": "{{jenkins_job}}"
      }
     ]
    },
    {
     "title": "Job IO Usage",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "default_jenkins_job_usage_bytes{job=~\"$job\", instance=~\"$instance\", jobName=~\"$jenkins_job\"}",
       "legendFormat": "{{jobName}}"
      }
     ]
    },
    {
     "title": "Job Score",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "default_jenkins_builds_health_score{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"}",
       "legendFormat": "{{jenkins_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Single Job Info (Select Single Job Name Before Opening)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Stage Duration",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_sum{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\"}\r\n",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Job Params",
     "type": "table",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "default_jenkins_builds_duration_milliseconds_summary_sum{job=~\"$job\", instance=~\"$instance\", jenkins_job=~\"$jenkins_job\", status=\"SUCCESS\"}",
       "legendFormat": "JOB={{jenkins_job}} / {{parameters}}"
      }
     ]
    }
   ]
  }
 ]
}