{
 "title": "Live Server Resources Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Monitoring Timeseries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mem Free",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\", job=~\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$node\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Free",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node\", job=~\"$job\", mountpoint=~\"/etc/hostname|/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node\", job=~\"$job\", mountpoint=~\"/etc/hostname|/\"} - node_filesystem_avail_bytes{instance=~\"$node\", job=~\"$job\", mountpoint=~\"/etc/hostname|/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sys Usage [$node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node IP",
     "type": "text",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "options": { "content": "# ${node}" },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])))) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(node_load15{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg_over_time(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) - avg_over_time(node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) / (avg_over_time(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) )) * 100"
      }
     ]
    },
    {
     "title": "IO Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, 100 - (avg_over_time(node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\", mountpoint=~\"/etc/hostname|/\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\", mountpoint=~\"/etc/hostname|/\"}[$__rate_interval]))\r\n"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, node_filesystem_size_bytes{instance=~\"$node\", job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"}"
      }
     ]
    }
   ]
  }
 ]
}