{
 "title": "SQL Server Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "sqlserver", "label": "sqlserver", "query": "mssql" }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections by database",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 9, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_connection_by_db_counter{instance=~\"$instance\"}",
       "legendFormat": "{{database_name}}"
      }
     ]
    },
    {
     "title": "Connections by database by session",
     "type": "table",
     "gridPos": { "h": 13, "w": 15, "x": 9, "y": 1 },
     "targets": [
      {
       "expr": "mssql_connection_by_db_by_session_counter{instance=~\"$instance\"}",
       "legendFormat": "{{database_name}} {{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MORE DIRECT QUERIES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host OS Info",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "-- MONITORING Grafana (Host OS Info)\r\nSELECT\r\n    [host_platform],\r\n    [host_distribution],\r\n    [host_release],\r\n    [host_architecture]\r\nFROM\r\n    [master].[sys].[dm_os_host_info]"
      }
     ]
    },
    {
     "title": "TOP X executed Queries details",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "-- MONITORING Grafana (TOP X executed Queries details)\r\nSELECT\r\n  TOP 10\r\n  text,\r\n  execution_count AS count,\r\n  creation_time,\r\n  last_execution_time,\r\n  total_rows,\r\n  total_worker_time,\r\n  last_worker_time,\r\n  total_elapsed_time,\r\n  last_elapsed_time,\r\n  min_elapsed_time,\r\n  max_elapsed_time,\r\n  total_used_grant_kb,\r\n  last_used_grant_kb,\r\n  min_used_grant_kb,\r\n  max_used_grant_kb,\r\n  -- Total Used Granted Memory in Kilobytes\r\n  total_grant_kb,\r\n  last_grant_kb,\r\n  min_grant_kb,\r\n  max_grant_kb\r\nFROM\r\n  sys.dm_exec_query_stats AS deqs\r\n  CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest\r\nORDER BY\r\n  count DESC;"
      }
     ]
    },
    {
     "title": "LAST X executed Queries details",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "-- MONITORING Grafana (LAST X executed Queries details)\r\nSELECT\r\n  TOP 10\r\n  text,\r\n  execution_count AS count,\r\n  creation_time,\r\n  last_execution_time,\r\n  total_rows,\r\n  total_worker_time,\r\n  last_worker_time,\r\n  total_elapsed_time,\r\n  last_elapsed_time,\r\n  min_elapsed_time,\r\n  max_elapsed_time,\r\n  total_used_grant_kb,\r\n  last_used_grant_kb,\r\n  min_used_grant_kb,\r\n  max_used_grant_kb,\r\n  -- Total Used Granted Memory in Kilobytes\r\n  total_grant_kb,\r\n  last_grant_kb,\r\n  min_grant_kb,\r\n  max_grant_kb\r\nFROM\r\n  sys.dm_exec_query_stats AS deqs\r\n  CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest\r\nORDER BY\r\n  last_execution_time DESC;"
      }
     ]
    },
    {
     "title": "LAST X MONITORING Queries details",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "-- MONITORING Grafana (LAST X MONITORING Queries details)\r\nSELECT\r\n  TOP 100\r\n  text,\r\n  execution_count AS count,\r\n  creation_time,\r\n  last_execution_time,\r\n  total_rows,\r\n  total_worker_time,\r\n  last_worker_time,\r\n  total_elapsed_time,\r\n  last_elapsed_time,\r\n  min_elapsed_time,\r\n  max_elapsed_time,\r\n  total_used_grant_kb,\r\n  last_used_grant_kb,\r\n  min_used_grant_kb,\r\n  max_used_grant_kb,\r\n  total_grant_kb,\r\n  last_grant_kb,\r\n  min_grant_kb,\r\n  max_grant_kb\r\nFROM\r\n  sys.dm_exec_query_stats AS deqs\r\n  CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest\r\nWHERE dest.text LIKE '-- MONITORING%'\r\nORDER BY last_execution_time DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Base Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_uptime{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Functions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_function_counter{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Schemas",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_schema_counter{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Procedures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_procedure_counter{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_session_counter{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_database_counter{instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_deadlock_counter{operation=\"count\", instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Master Files Read Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_size{instance=~\"$instance\", operation=\"read_size_bytes\"}",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    },
    {
     "title": "Database Master Files Write Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_size{instance=~\"$instance\", operation=\"write_size_bytes\"}",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    },
    {
     "title": "Database Master Files Total Size",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_size{instance=~\"$instance\", operation=\"total_size_bytes\"} *8  /1024 /1024",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stall IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Master Files Read Stall",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_stall{instance=~\"$instance\", operation=\"read_stall_ms\"}",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    },
    {
     "title": "Database Master Files Write Stall",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_stall{instance=~\"$instance\", operation=\"write_stall_ms\"}",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    },
    {
     "title": "Database Master Files Total Stall",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "mssql_dbs_io_stall{instance=~\"$instance\", operation=\"total_stall_ms\"}",
       "legendFormat": "{{database}}-{{file_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network input by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mssql_network_bytes{instance=~\"$instance\", interface=~\".*:\", operation=\"input_bytes\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network output by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mssql_network_bytes{instance=~\"$instance\", interface=~\".*:\", operation=\"output_bytes\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network input packets by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mssql_network_packets{instance=~\"$instance\", interface=~\".*:\", operation=\"input_count\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network output packets by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mssql_network_packets{instance=~\"$instance\", interface=~\".*:\", operation=\"output_count\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minimum",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "max by(name) (mssql_sys_config_defaults{instance=~\"$instance\", operation=~\"minimum\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Maximum",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 6 },
     "targets": [
      {
       "expr": "max by(name) (mssql_sys_config_defaults{instance=~\"$instance\", operation=~\"maximum\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Value",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "max by(name) (mssql_sys_config_defaults{instance=~\"$instance\", operation=~\"value\", instance=~\"$instance\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Value In Use",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 6 },
     "targets": [
      {
       "expr": "max by(name) (mssql_sys_config_defaults{instance=~\"$instance\", operation=~\"value_in_use\", instance=~\"$instance\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks by Resource Type",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "mssql_locks_by_resource_type{resource_type=~\".*\", instance=~\"$instance\"}\r\n",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Locks by Resource Database",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "mssql_locks_by_resource_database{database_name=~\".*\", instance=~\"$instance\"}",
       "legendFormat": "{{database_name}}"
      }
     ]
    },
    {
     "title": "Locks by Request Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "mssql_locks_by_request_status{request_status=~\".*\", instance=~\"$instance\"}",
       "legendFormat": "{{request_status}}"
      }
     ]
    },
    {
     "title": "Locks by Request Mode",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "mssql_locks_by_request_mode{request_mode=~\".*\", instance=~\"$instance\"}",
       "legendFormat": "{{request_mode}}"
      }
     ]
    },
    {
     "title": "Locks by Request Type",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "mssql_locks_by_request_type{request_type=~\".*\", instance=~\"$instance\"}",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Locks by Request Owner Type",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "mssql_locks_by_request_owner_type{request_owner_type=~\".*\", instance=~\"$instance\"}",
       "legendFormat": "{{request_owner_type}}"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "mssql_deadlock_counter{operation=\"count\", instance=~\"$instance\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latest Deadlock Details",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "mssql_deadlock_details{instance=~\"$instance\"}",
       "legendFormat": "{{request_status}}"
      }
     ]
    }
   ]
  }
 ]
}