services:
  terraform-cli:
    container_name: terraform-cli
    volumes:
      - .:/terraform
    image: hashicorp/terraform
    entrypoint: ""
    command: "tail -f /dev/null"
    working_dir: /terraform
    tty: true

