version: "3"

services:
  grafana:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: local/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      # - LDAP_ADMIN_PASSWORD=$
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-default}
      - GF_AUTH_LDAP_ENABLED=${GF_AUTH_LDAP_ENABLED:-false}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-adminadmin123}
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource,grafana-clock-panel
      # grafana-image-renderer related params
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    networks:
      - monitoring
    env_file:
      - ../../.global.env
  grafana-image-renderer:
    container_name: grafana-image-renderer
    hostname: grafana-image-renderer
    restart: always
    image: grafana/grafana-image-renderer:3.8.4
    environment:
      - RENDERING_ARGS=--no-sandbox,--disable-gpu,--window-size=1280x758
    # ports:
    #   - 8081:8081
    networks:
      - monitoring
networks:
  monitoring:
volumes:
  grafana-data:
