---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: geerlingguy
    - COLLECTION_NAME: k8s
  matrix:
    - MOLECULE_DISTRO: default

install:
  # Install test dependencies.
  - pip install ansible molecule yamllint ansible-lint docker openshift

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Run test-manifests scenario.
  - molecule test -s test-manifests

deploy:
  provider: script
  script: ansible-playbook -i 'localhost,' scripts/deploy.yml -e "tag=$TRAVIS_TAG"
  'on':
    tags: true
    condition: $MOLECULE_DISTRO = default
