apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: test-http-chaos
  namespace: default
spec:
  mode: all
  selector:
    labelSelectors:
      app: nginx
    namespaces:
      - default      
  target: Response
  port: 80
  method: GET
  path: "/"
  # abort: true
  duration: 5s