scrape_configs:
  - job_name: "kubernetes-pods"
    scheme: http
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      # - source_labels: [__meta_kubernetes_namespace]
      #   action: replace
      #   target_label: namespace
      # - source_labels: [__meta_kubernetes_pod_name]
      #   action: replace
      #   target_label: pod
    # metric_relabel_configs:
    #   - source_labels: [__name__]
    #     regex: "node.*|process.*"
    #     action: keep
