scrape_configs:
  - job_name: "kubernetes-services"
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)

# Metrics authentication.*|etcd.*|field_validation.*|serviceaccount.*|registered_metric_total|pod.*|node.*|kubernetes.*|kube.*|grpc.*