scrape_configs:
  - job_name: "kubernetes-nodes"
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)



# Metrics: force.*|hidden_metrics.*|kubelet.*|reconstruct_volume.*|volume.*|storage.*