apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  type: ClusterIP
  ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
      # nodePort: 30910
  selector:
    app: node-exporter
  sessionAffinity: None
