global:
  scrape_interval: 15s

scrape_config_files:
  - scrape-configs/docker/node-exporter.yml
  - scrape-configs/docker/cadvisor.yml
  - scrape-configs/docker/awaragi-mssql-exporter.yml
  - scrape-configs/docker/sql-exporter.yml
  - scrape-configs/docker/prometheus.yml
  - scrape-configs/docker/blackbox.yml
  # Cluster monitoring
  - scrape-configs/docker/kubernetes/node-exporter.yml
  - scrape-configs/docker/kubernetes/cadvisor.yml
  - scrape-configs/docker/kubernetes/kube-state-metrics.yml
  # Jenkins monitoring
  - scrape-configs/docker/jenkins.yml

# Federation (scrape from distant prometheus)
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~".*"}'
        # - '{job="prometheus}'
        # - '{__name__=~"job:.*"}'
    static_configs:
      - targets:
        - 'xxx.xxx.xxx.xxx:9090'


# scrape_configs:
rule_files:
  - "scrape-configs/alerts/alert-rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
