global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        instance: 'localhost'
    # - targets: ['host.docker.internal:7081']
    #   labels:
    #     instance: 'nginx-secure'
    # basic_auth:
    #   username: "admin"
    #   password_file: /etc/prometheus/passwd
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - cadvisor:8080    

  # - job_name: 'nginx'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: 
  #       - nginx-exporter:9113
    # basic_auth:
    #   username: root
    #   password: aaaa     

  - job_name: 'mssql-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'mssql-exporter:4000'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://www.google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
      # Make sure this matches the service name
        replacement: "blackbox-exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
rule_files:
  - "alert-rules.yml"
