version: "3.5"

services:
  mongo:
    # image: mongo:latest
    image: mongo:4.4.6
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
  # https://hub.docker.com/_/mongo-express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb:27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - mongo
    depends_on:
      - mongo

networks:
  mongo:
volumes:
  mongodb-data:
    name: mongodb-data
  mongodb-config:
    name: mongodb-config