---
- name: Converge
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  roles:
    - helm
    - k8s_manifests

- import_playbook: '{{ playbook_dir }}/asserts.yml'
