concurrent = 5
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "slave-runner"
  url = "https://gitlab.url/"
  token = "MYTOKEN"
  executor = "docker"
  pre_build_script = "touch /tmp/myfile\n ls /tmp"

  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/home/gitlab-runner/.ssh:/root/.ssh", "/home/docker/mywebsite.crt:/etc/gitlab-runner/certs/mywebsite.crt:ro"]
    extra_hosts = ["my.domain.example:XXX.XXX.XXX.XXX"]
    shm_size = 0
