global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - node-exporter:9100

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - cadvisor:8080

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

rule_files:
  - "alert-rules.yml"
