apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1.14.2
spec:
  selector:
    matchLabels:
      app: nginx1.14.2
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nginx1.14.2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
          - name: nginx-persistent-storage # Volume name
            mountPath: /usr/share/nginx/html # data to persist from container inside
      volumes:
        - name: nginx-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          # check storage.yaml file
          persistentVolumeClaim:
            claimName: nginx-pvc # nginx Persistant volume
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx1.14.2 # Service pod label selector
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

