server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Get container logs for containers with labels like this only
    # labels:
    #   logging: "promtail"
    #   logging_jobname: "containerlogs"

  # - job_name: docker
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: docker_logs
  #         __path__: /var/lib/docker/containers/*/*-json.log
  # Get all container logs
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

