apm-server:
  host: "0.0.0.0:8200"
  secret_token: ${APM_SECRET_KEY}
  rum.enabled: true
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}