client:
  hosts:
    - host.docker.internal
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

# logging:
#   loglevel: INFO
#   logfile: /var/log/curator.log
#   logformat: default
#   blacklist: []

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elastic_transport', 'urllib3']
