all:
  hosts:
    myawsinstance1:
      ansible_host: cac_ansible_worker_1
      ansible_user: root
      ansible_password: root
      ansible_port: 22
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
