apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx1.14.2 # Service pod label selector
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

# kubectl apply -f nginx-service.yaml    
