{
 "title": "Alertmanager",
 "description": "alert manager example",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Alertmanager Instance",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "All alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "alertname!=\"Watchdog\", component!=\"monitoring\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"KubeNodeNotReady\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "High CPU Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"HighCpuLoad\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "High Memory Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"OutOfMemory\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "alertname=\"Watchdog\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Severity: P1",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "severity=\"P1\", component!=\"monitoring\"",
     "labelSelector": "*",
     "legendFormat": "instance",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  { "title": "Error and Warning Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Severity: P2",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "severity=\"P2\",  component!=\"monitoring\"",
     "labelSelector": "*",
     "legendFormat": "instance",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Severity: P3",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "severity=\"P3\",  component!=\"monitoring\"",
     "labelSelector": "*",
     "legendFormat": "instance",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}