collector_name: mssql_time
# Similar to global.min_interval, but applies to the queries defined by this collector only.
min_interval: 0s
metrics:
  # - metric_name: mssql_local_time_seconds
  #   type: gauge
  #   help: "Local time in seconds since epoch (Unix time)."
  #   values: [unix_time]
  #   query: |
  #     SELECT DATEDIFF(second, '19700101', GETUTCDATE()) AS unix_time

  - metric_name: mssql_uptime
    type: gauge
    help: "Instance start time."
    values: [start_time]
    query: |
      -- MONITORING sql-exporter (mssql_uptime)
      SELECT
          start_time = CAST(DATEDIFF_BIG(millisecond, sqlserver_start_time, GETDATE()) AS BIGINT)
      FROM sys.dm_os_sys_info;

