---
- name: Install apache2 server
  hosts: all  # Replace with the actual hostname or IP address of your target host
  become: true

  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'
      
    - name: Create The HTML File
      shell: echo "Hello From The Ansible Challenge" > /var/www/html/index.html
      args:
        executable: /bin/bash
      notify:
        - Reload Apache

    - name: Get Public Ip
      shell: curl ifconfig.me
      args:
        executable: /bin/bash
      when: ansible_distribution == 'Ubuntu'
      register: public_ip

    - name: Print Ip Address
      debug:
        var: public_ip.stdout_lines        

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: started
      when: ansible_distribution == 'Ubuntu'

