apm-server:
  # ilm:
  #   enabled: "auto"
  #   setup:
  #     enabled: true
  #     overwrite: true
  #     require_policy: true
  #     mapping:
  #       - event_type: "error"
  #         policy_name: "apm-rollover-policy"
  #         index_suffix: ""
  #       - event_type: "span"
  #         policy_name: "apm-rollover-policy"
  #         index_suffix: ""
  #       - event_type: "transaction"
  #         policy_name: "apm-rollover-policy"
  #         index_suffix: ""
  #       - event_type: "metric"
  #         policy_name: "apm-rollover-policy"
  #         index_suffix: ""
  #       - event_type: "profile"
  #         policy_name: "apm-rollover-policy"
  #         index_suffix: ""
  #     policies:
  #       - name: "apm-rollover-policy"
  #         policy:
  #           phases:
  #             hot:
  #               min_age: 0ms
  #               actions:
  #                 rollover:
  #                   max_size: 5kb
  #                   max_age: 30s
  #                   max_docs: 100
  #                 set_priority:
  #                   priority: 10000
  #             warm:
  #               actions:
  #                 set_priority:
  #                   priority: 10000
  #             cold:
  #               min_age: 0s
  #               actions:
  #                 set_priority:
  #                   priority: 10000
  #         delete:
  #           min_age: "3m"
  #           actions:
  #             delete: {}
  #             #   delete_searchable_snapshot: true    


  host: "0.0.0.0:8200"
  # secret_token: ${APM_SECRET_KEY}
  rum:
    enabled: true
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}


