apm-server:
  ilm:
    enabled: "auto"
    setup:
      enabled: true
      overwrite: true
      require_policy: true
      mapping:
        - event_type: "profile"
          policy_name: "apm-default-policy"
          index_suffix: ""
        - event_type: "error"
          policy_name: "apm-default-policy"
          index_suffix: ""
        - event_type: "metric"
          policy_name: "apm-metrics-policy"
          index_suffix: ""
        - event_type: "span"
          policy_name: "apm-span-transaction-policy"
          index_suffix: ""
        - event_type: "transaction"
          policy_name: "apm-span-transaction-policy"
          index_suffix: ""
      policies:
          # will persist 7 - 22 days of default data
        - name: "apm-default-policy"
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "50mb"
                    max_age: "15d"
              delete:
                min_age: "7d"
                actions:
                  delete: {}
        - name: "apm-metrics-policy"
          # will persist 2 - 4 days of metrics data
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "1gb"
                    max_age: "2d"
              delete:
                min_age: "2d"
                actions:
                  delete: {}
        - name: "apm-span-transaction-policy"
          # will persist 30 days of transaction data
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "100mb"
                    max_age: "1d"
              delete:
                min_age: "15d"
                actions:
                  delete: {}
  host: "0.0.0.0:8200"
  # secret_token: ${APM_SECRET_KEY}
  rum:
    enabled: true
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}


