# Make sure /home/gitlab-runner/.ssh directory is copied under /root/.ssh to authenticate using ssh
stages:
  - committingJob

committingJob:
  image: 
    name: bitnami/git
  stage: committingJob
  script:
    - git remote set-url origin "git@<SOME_URL_HERE>:${CI_PROJECT_PATH}.git"
    # - git remote rm origin 
    # - git remote add origin "git@<SOME_URL_HERE>:${CI_PROJECT_PATH}.git"
    - git config user.name "user"
    - git config user.email "user@example.com"
    # - git config --global http.sslverify "false"
    - touch README.md
    - echo "AA" >>README.md
    - git add .
    # Can either use[skip ci] [ci skip] or -o ci.skip
    # https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-gitlab-cicd
    - git commit -m "A commit message [skip ci]"
    - git push -o ci.skip origin HEAD:$CI_COMMIT_REF_NAME


