version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8090:8080
      - 50000:50000      
    volumes:
      - jenkins-data:/var/jenkins_home   
volumes:
  jenkins-data:
