---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/app1
  storageClassName: standard