---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app1-pvc
  namespace: app1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard