---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-pvc
  namespace: alpine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: "pv-app1"
