version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "6831:6831"
  python-app:
    container_name: python-app
    build:
      context: ./python-app
      dockerfile: Dockerfile
    image: python-app
    ports:
      - 5000:5000
    depends_on:
      - jaeger