version: '3'

services:
  prometheus:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: local/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always    
    ports:
      - 6008:9090
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/docker-prometheus.yml'
      - '--storage.tsdb.retention.time=72h'
      # - --storage.tsdb.retention.size=2GB
      # Uncomment to Allow admin apis (e.g to delete job data)
      # example: curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={job="kubernetes-kube-state-metrics"}'
      # - '--web.enable-admin-api'          
    networks:
      - monitoring
    extra_hosts:
        - "host.docker.internal:host-gateway"      
networks:
  monitoring:
volumes:
  prometheus-data:
  
