apiVersion: v1
kind: Namespace
metadata:
   name: nginx-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: nginx-namespace
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx   

# kubectl apply -f .
# kubectl get all -n nginx-namespace
# kubectl delete ns nginx-namespace