version: '3.3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash
    entrypoint: ""
    tty: true