version: '3'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/config.toml:/etc/gitlab-runner/config.toml
      - ./certs:/etc/gitlab-runner/certs
    restart: always
