version: '3'

services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    entrypoint: ""
    command: bash
    tty: true
    environment:
      RUNNER_NAME: "lqss-runner"
      CI_SERVER_URL: "https://gitlab.url/"
      REGISTRATION_TOKEN: "GR1341234...vCWKR"
      DOCKER_IMAGE: "alpine"
      CI_SERVER_TLS_CA_FILE: "/etc/gitlab-runner/certs/gitlab_ca.crt"
      RUNNER_EXECUTOR: "docker"
      REGISTER_NON_INTERACTIVE: "true"
    volumes:
      - ./config:/etc/gitlab-runner
