apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor
  name: cadvisor
spec:
  ports:
  - name: cadvisor
    nodePort: 30880
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cadvisor
  type: NodePort