---
- name: Install packages 
  hosts: all
  become: true
  vars:
    packages:
      - apache2
      - nano
      - vim
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install packages
      loop: "{{ packages }}"
      apt:
        name: "{{ item }}"
        state: present
      when: ansible_distribution == 'Ubuntu'
   
    - name: Remove packages
      loop: "{{ packages }}"
      apt:
        name: "{{ item }}"
        state: absent
      when: ansible_distribution == 'Ubuntu'

