- name: strategy example
  hosts: all
  become: true
  strategy: free
  serial: 
    - 2
    - 1 
  tasks:
    - name: Curl AWS
      shell: curl -I google.com
      register: curl
    - name: Print "Hello World!"
      debug:
        # msg: "Hello World!"
        # changed | cmd | delta | end | msg | rc | start | stderr | stderr_lines | stdout | stdout_lines
        var: curl.stdout        