apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-rbac
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  # This is for the following apis
  # http://localhost:8080/api/v1/nodes/k8s-cluster-control-plane/proxy/metrics/cadvisor
  # http://localhost:8080/api/v1/nodes/k8s-cluster-control-plane/proxy/metrics
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
