scrape_configs:
  - job_name: "kubernetes-cadvisor-from-cluster"
    scheme: https
    metrics_path: /metrics/cadvisor
    kubernetes_sd_configs:
      - role: node
        api_server: https://kubernetes.docker.internal:6443
        tls_config:
          insecure_skip_verify: true
        # kubectl -n <namespace> create token <service-account> >token
        bearer_token_file: token
    bearer_token_file: token
    tls_config:
      insecure_skip_verify: true

    metric_relabel_configs:
      - source_labels: [pod]
        target_label: name
