version: '3'
services:
  dockeragent:
    build: 
      dockerfile: Dockerfile.${AGENT_VARIANT:-dind}
      context: .
    privileged: true
    container_name: azuredevops_agent_${AGENT_VARIANT:-dind}
    image: azuredevopsagent:${AGENT_VARIANT:-dind}
    env_file:
      - .env
