version: "3"

services:
  portainer-agent:
    image: portainer/agent:${VERSION:-2.20.3-alpine}
    container_name: portainer-agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
