version: "3.8"
services:
  web:
    image: nginx
    depends_on:
      redis:
        condition: service_healthy # This checks for health
  redis:
    image: redis
    # try to run a random command that doesn't exist 
    # it would cause the the service to be unhealthy
    #command: random_cmd
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30