version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8880:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      custom_net:
        ipv4_address: 172.18.0.2

  apache:
    image: httpd:alpine
    container_name: httpd
    ports:
      - 8881:80
    networks:
      custom_net:
        ipv4_address: 172.18.0.35

  tomcat:
    image: tomcat:alpine
    container_name: tomcat
    ports:
      - 8882:8080
    networks:
      custom_net:
        ipv4_address: 172.18.0.55

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
