apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh:full
subjects:
- kind: ServiceAccount
  name: chaos-daemon
  namespace: default
- kind: ServiceAccount
  name: chaos-dashboard
  namespace: default
- kind: ServiceAccount
  name: chaos-dns-server
  namespace: default
- kind: ServiceAccount
  name: chaos-controller-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: full
  apiGroup: rbac.authorization.k8s.io
