global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dockerd-exporter'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['dockerd-exporter:9323']