scrape_configs:
  - job_name: "kubernetes-coredns"
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: "kube-dns"
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: "9153"
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "coredns.*"
        action: keep