scrape_configs:
  - job_name: "kubernetes-kube-state-metrics"
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: "kube-state-metrics"
        action: keep
      # Ignore telemetry metrics
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: "8081"
        action: drop
    metric_relabel_configs:
      - source_labels: [instance]
        target_label: cluster
        replacement: "$1"
        regex: "(.+):.+"
      - source_labels: [__name__]
        regex: "go.*|process.*"
        action: drop
