{
 "title": "Apiserver",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\".*apiserver.*\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\".*apiserver.*\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Server - Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETCD Lead Object Counts Sum",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_lease_object_counts_sum{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - GET",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"get\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - CREATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"create\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - DELETE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"delete\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - LIST",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"list\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - ListWithCount",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"listWithCount\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ETCD Request Duration - UPDATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "etcd_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", operation=\"update\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - Errors by verb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"$job\", instance=\"$instance\"}[$__rate_interval]))\r\n / sum by(verb) (rate(apiserver_request_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "API Server - Errors by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{code=~\"5..\", job=\"$job\", instance=\"$instance\"}[$__rate_interval]))\r\n / sum by(instance) (rate(apiserver_request_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - HTTP Requests by code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (code) (rate(apiserver_request_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "API Server - HTTP Requests by verb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (verb) (rate(apiserver_request_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "API Server - Stacked HTTP Requests by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - HTTP Requests Latency by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)\r\n/\r\nsum(rate(apiserver_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "API Server - HTTP Requests Latency Percentile",
     "type": "graph",
     "description": "95th percentile request latency for Kubernetes apiserver component",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s", "label": "latency" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
       "legendFormat": "p50 "
      }
     ]
    },
    {
     "title": "API Server - HTTP Requests Latency by verb",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (verb)\r\n/\r\nsum(rate(apiserver_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (verb)",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - Work Queue by instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_depth{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Server - Work Queue Processing Time Percentile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s", "label": "processing time" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "API Server - Work Queue Service Time Percentile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "s", "label": "service time" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  }
 ]
}