{
 "title": "KSM Pods information",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info,container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(avg_over_time(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[1m]), \"tag\", \"$1\", \"image\", \".*:([^:]+)$\")"
    }
   ]
  },
  {
   "title": "CLUSTER $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Pods information",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "label_replace(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}, \"tag\", \"$1\", \"image\", \".*:([^:]+)$\")\r\n"
      }
     ]
    },
    {
     "title": "Pods information",
     "type": "table",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}"
      }
     ]
    },
    {
     "title": "Service + deployment info",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kube_service_spec_type{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_service_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(kube_deployment_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}, \"service\", \"$1\", \"deployment\", \"(.*)\")\r\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Containers Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "(time() - kube_deployment_created{cluster=~\"$cluster\",namespace=~\"$namespace\",})/86400",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}