version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    image: nodejs-backend
    restart: always
    environment:
      NODE_ENV: production
      LOGGING_FORMAT: json

      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: mydb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - backend_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb # Initial database
    ports:
      - '3306:3306'
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql-storage:

networks:
  backend_network:
    driver: bridge
