---
- name: Configure IPv4 forwarding and iptables for bridged traffic
  hosts: all
  become: yes

  tasks:
    - name: Create k8s.conf for module loading
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf

    - name: Load kernel module overlay
      command: modprobe overlay
      ignore_errors: yes

    - name: Load kernel module br_netfilter
      command: modprobe br_netfilter
      ignore_errors: yes

    - name: Create k8s.conf for sysctl settings
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply sysctl settings
      command: sysctl --system
      ignore_errors: yes
