---
- name: Update and install containerd
  hosts: all
  become: yes

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd
        state: present