version: '3'

services:  
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    hostname: node-exporter
    restart: always    
    ports:
      - "6007:9100"  
    networks:
      - monitoring
networks:
  monitoring: