- name: web
  hosts: myawsinstance1
  become: true
  vars:
    my_variable: "Hello, Ansible!"
  tasks:
    - name: Curl AWS
      shell: curl localhost
      args:
        chdir: /home/ubuntu/
        executable: /bin/bash
      register: curl
    - name: Print "Hello World!"
      debug:
        # msg: "Hello World!"
        # changed | cmd | delta | end | msg | rc | start | stderr | stderr_lines | stdout | stdout_lines
        var: curl.cmd        
