version: '3'

services:  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    restart: always
    ports:
      - "9113:9113"
    command:
      -nginx.scrape-uri=http://nginx:80/metrics -web.telemetry-path=/metrics
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 7080:80
    volumes:
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf