version: "3.8"
services:
  ansible_controller:
    container_name: ansible_controller
    build: 
      context: ../..
      dockerfile: "docker/images/Dockerfile.ansible.alpine"
    volumes:
      - ../:/playground
      - ./.ssh:/root/.ssh
    working_dir: /playground
    networks:
      - ansible      
  ansible_worker:
    build: 
      context: ../..
      dockerfile: "docker/images/Dockerfile.ssh.ubuntu"
    volumes:
      - ../:/playground
      - ./.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    working_dir: /playground
    networks:
      - ansible      
networks:
  ansible: