apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      workload: cicd
  replicas: 1
  template: 
    metadata:
      labels:
        app: mysql 
        workload: cicd        
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.32
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-db-name 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: mysql-secret
                key: mysql-root-pass
      restartPolicy: Always        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
    workload: cicd    
  ports:
    - name: http
      port: 3306
  type: ClusterIP