# Must read more https://www.serverlab.ca/tutorials/containers/kubernetes/deploy-phpmyadmin-to-kubernetes-to-manage-mysql-pods/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  selector:
    matchLabels:
      app: pma
      workload: cicd
  replicas: 1
  template: 
    metadata:
      labels:
        app: pma 
        workload: cicd        
    spec:
      containers:
      - name: pma
        image: phpmyadmin/phpmyadmin:5.1.1
        env:
        - name: PMA_HOST
          value: "mysql-service"
      restartPolicy: Always        
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  selector:
    app: pma
    workload: cicd    
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort