version: '3.8'
services:
  influxdb:
    image: influxdb:2.0-alpine
    container_name: influxdb
    ports:
        - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    restart: on-failure:15
volumes:
  influxdb-storage: