version: '3'

services:  
  secure-exporter:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile  
    image: local/secure-exporter
    container_name: secure-exporter
    hostname: secure-exporter
    restart: always
    ports:
      - 6006:9100
    networks:
      - monitoring
networks:
  monitoring:        
