version: '3.3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8880:80
    entrypoint: 
      - /bin/sh
      - -c
      - >
        echo 'server {
          listen 80;
          server_name localhost;

        location /api/ {
            proxy_pass http://host.docker.internal:9000/api/;
            proxy_redirect off;

            # Allow the use of websockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $$host;
            proxy_cache_bypass $$http_upgrade;
        }

          location / {
            proxy_pass http://host.docker.internal:9000/;
            proxy_redirect off;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
          }
        }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
