apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
