# Use root/root as user/password credentials
version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER:  test 
      # MYSQL_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      mariadb:
        # ports:
        #     - "3306:3306"      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      mariadb:      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8889:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      mariadb:      
volumes:
  mariadb:
networks:
  mariadb:
