# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: my-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/data
#   storageClassName: standard
# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: "pv-app1"  
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: my-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/data
#   storageClassName: standard