kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role
  namespace: default
rules:
  - apiGroups: [""] # Core API groups
    # resources: ["pods","deployments","services"]
    resources:
      - pods
      - pods/log
      - services
    verbs: ["get", "list", "watch"]
