apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault:full
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default
roleRef:
  kind: ClusterRole
  name: full
  apiGroup: rbac.authorization.k8s.io
