apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-secret
  annotations:
    kubernetes.io/service-account.name: vault

# kubectl -n default describe secret vault-secret