version: "3.3"
services:
  vault-server:
    image: vault:1.13.3
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "token"
    cap_add:
      - IPC_LOCK
    volumes:
      - hashicorp-vault:/vault
volumes:
  hashicorp-vault: