{
 "title": "Nginx Json Logs dashboard",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Service",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "loki", "label": "loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "table",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{container=\"$container\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\" | json"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
     "options": {
      "content": "# Nginx Monitoring\n\n## Prerequisites\n\nTo use this dashboard, ensure you have JSON-formatted Nginx logs coming from a Promtail/Loki datasource.\n\n## Configuration Example\n\nTo set up your Nginx logs for monitoring, follow these steps:\n\n1. **Edit the Log Format:**\n   \n   Open your `/etc/nginx/nginx.conf` file and configure the log format to JSON by adding the following lines:\n\n   ```nginx\n   log_format main escape=json '{'\n                   '\"timestamp\":\"$time_iso8601\",'\n                   '\"source\":\"$server_addr\",'\n                   '\"hostname\":\"$hostname\",'\n                   '\"ip\":\"$http_x_forwarded_for\",'\n                   '\"client\":\"$remote_addr\",'\n                   '\"request_method\":\"$request_method\",'\n                   '\"scheme\":\"$scheme\",'\n                   '\"domain\":\"$server_name\",'\n                   '\"referer\":\"$http_referer\",'\n                   '\"request\":\"$request_uri\",'\n                   '\"args\":\"$args\",'\n                   '\"size\":$body_bytes_sent,'\n                   '\"status\":$status,'\n                   '\"responsetime\":$request_time,'\n                   '\"upstreamtime\":\"$upstream_response_time\",'\n                   '\"upstreamaddr\":\"$upstream_addr\",'\n                   '\"http_user_agent\":\"$http_user_agent\",'\n                   '\"https\":\"$https\"'\n                   '}';\n   ```\n\n2. **Specify the Log File:**\n   \n   Ensure the access log uses the `main` log format by adding or modifying the following line:\n\n   ```nginx\n   access_log /var/log/nginx/access.log main;\n   ```\n\n3. **Deploy and Connect to Loki:**\n   \n   After configuring the log format and log file, deploy your Nginx configuration. Then, link your logs from Loki. You should see all the specified fields in the monitoring dashboard.\n\nBy following these steps, your Nginx logs will be formatted correctly for JSON processing and monitoring through Loki, providing detailed insights into your web server's activity."
     }
    }
   ]
  }
 ]
}