network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: false
      dhcp6: false
      addresses:
        - 10.0.0.9/24
        - 2041:0:140F::875B:131B/64
      nameservers:
        addresses:
          - 10.0.0.1
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 192.168.0.0/24
          via: 10.0.0.100
        - to: default
          via: 10.0.0.1
