# http://localhost:8080/api/v1/nodes/k8s-cluster-control-plane/proxy/metrics
scrape_configs:
  - job_name: "kubernetes-cadvisor-from-cluster"
    scheme: https
    metrics_path: /metrics/cadvisor
    tls_config:
      # ca_file: /etc/prometheus/certs/ca.pem
      key_file: /etc/prometheus/certs/key.pem
      cert_file: /etc/prometheus/certs/cert.pem
      insecure_skip_verify: true
    # authorization:
    #   credentials_file: /etc/prometheus/certs/token
    kubernetes_sd_configs:
      - role: node
        api_server: 'https://192.168.1.27:6443'
        tls_config:
          # ca_file: /etc/prometheus/certs/ca.pem
          key_file: /etc/prometheus/certs/key.pem
          cert_file: /etc/prometheus/certs/cert.pem
          insecure_skip_verify: true
        # kubeconfig_file: /etc/prometheus/certs/config 
    metric_relabel_configs:
      - source_labels: [pod]
        target_label: name
