# https://github.com/elastic/apm-server/blob/main/apm-server.yml
apm-server:
  ilm:
    # https://www.elastic.co/guide/en/elasticsearch/reference/7.10/ilm-index-lifecycle.html#ilm-phase-transitions
    enabled: "auto"
    setup:
      enabled: true
      overwrite: true
      require_policy: true
      mapping:
        - event_type: "profile"
          policy_name: "apm-default-policy"
          index_suffix: ""
        - event_type: "error"
          policy_name: "apm-default-policy"
          index_suffix: ""
        - event_type: "metric"
          policy_name: "apm-metrics-policy"
          index_suffix: ""
        - event_type: "span"
          policy_name: "apm-span-transaction-policy"
          index_suffix: ""
        - event_type: "transaction"
          policy_name: "apm-span-transaction-policy"
          index_suffix: ""
      policies:
          # will persist 7 - 22 days of metrics data
        - name: "apm-default-policy"
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "50mb"
                    max_age: "15d"
              delete:
                min_age: "7d"
                actions:
                  delete: {}
        - name: "apm-metrics-policy"
          # will persist 2 - 4 days of metrics data
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "1gb"
                    max_age: "2d"
              delete:
                min_age: "2d"
                actions:
                  delete: {}
        - name: "apm-span-transaction-policy"
          # will persist 30 days of transaction data
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "100mb"
                    max_age: "1d"
              delete:
                min_age: "15d"
                actions:
                  delete: {}
          # policy:
          #   phases:
          #     hot:
          #       min_age: 0ms
          #       actions:
          #         rollover:
          #           max_size: 5kb
          #           max_age: 30s
          #           max_docs: 100
          #         set_priority:
          #           priority: 10000
          #     warm:
          #       actions:
          #         set_priority:
          #           priority: 10000
          #     cold:
          #       min_age: 0s
          #       actions:
          #         set_priority:
          #           priority: 10000
          #     delete:
          #       min_age: 1s
          #       actions: {}      
  host: "0.0.0.0:8200"
  # secret_token: ${APM_SECRET_KEY}
  rum:
    enabled: true
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}