version: '3'
services:
  redis-stack:
    container_name: redis-stack
    hostname: redis-stack
    image: redis/redis-stack:latest
    restart: always
    ports:
    - "8001:8001"
    - "6379:6379"