# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # Deployment pod label selector
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: nginx # Pod Label for the Deployment selector
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx # Service pod label selector
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort


# You can start this file with apply -f /src/kubernetes/Deployments/nginx-deployment.yaml