# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # Deployment pod label selector
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nginx # Pod Label for the Deployment selector
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
