version: '3.8'

services:
  pyapp:
    container_name: pyapp
    hostname: pyapp
    build: .
    tty: true
    entrypoint: bash
    volumes:
      - .:/usr/src/app
  selenium:
    container_name: selenium
    hostname: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900" 
    environment:
      - VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    
