version: "3.7"
services:
    # create powerful visualizations with kibana
    kibana: 
      restart: always
      container_name: kibana
      hostname: kibana
      build:
        context: ..
        dockerfile: ./docker/Dockerfile
        args:
          VERSION: "${ELK_VERSION}"
      image: local/kibana
      ports:
        - "5601:5601"
      environment:
        ELASTIC_USERNAME: ${ELASTIC_USERNAME}
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      # volumes:
      #   - ../config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      networks:
        - logs-monitoring
networks:
  logs-monitoring:
