version: '3'

services:  
  alertmanager:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: local/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    ports:
      - 6002:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always
    networks:
      - monitoring
networks:
  monitoring:        